export interface ArtifactRef {
  path: string;
  mimeType: string;
  description: string;
}

export type AgentRunStatus = "planned" | "working" | "blocked" | "completed" | "failed" | "exited";

/** A durable, user-addressable agent assignment within a mission. */
export interface AgentRun {
  id: string;
  handle: string;
  displayName: string;
  taskId: string;
  subtaskId: string;
  role: string;
  modelRole: string;
  /** The initial goal shown as soon as the agent is spawned. */
  initialGoal?: string;
  /** The orchestrator's latest concrete assignment after preflight. */
  activeAssignment?: string;
  /** Concrete model used by this run, when resolved. */
  model?: string;
  /** Human-readable cost/capability rationale for the model choice. */
  modelReason?: string;
  status: AgentRunStatus;
  startedAt?: string;
  finishedAt?: string;
  summary?: string;
  pokemonName?: string;
  pokemonImage?: string;
}

export interface AgentWorkspaceSnapshot {
  agentId: string;
  files: {
    handsOn: string | null;
    handOff: string | null;
    proofOfWork: string | null;
    incompleteWork: string | null;
  };
}

export type MissionNextAction =
  | "review_plan"
  | "resume_checkpoint"
  | "continue_work"
  | "review_results"
  | "none";

export interface MissionSnapshot {
  task: {
    id: string;
    prompt: string;
    status: string;
    createdAt: string;
    topic: string | null;
  };
  plan: TaskPlan | null;
  agents: AgentRun[];
  latestLedger: LedgerEntry | null;
  checkpoints: Array<{
    from: string;
    summary: string;
    artifacts: ArtifactRef[];
  }>;
  nextAction: MissionNextAction;
}

/** A durable discussion space inside a mission. */
export interface Conversation {
  id: string;
  taskId: string;
  /** `public` is visible to the whole mission; agent threads are scoped to an agent. */
  kind: "public" | "agent_thread";
  title: string;
  participantIds: string[];
  agentId?: string;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string;
}

export type ConversationAuthorKind = "user" | "orchestrator" | "agent" | "system";

export interface Mention {
  /** The exact, canonical handle that appeared in the message, for example `@sage-1`. */
  handle: string;
  recipientId: string;
  recipientKind: "orchestrator" | "agent";
}

/** A durable message shown in a public conversation or a private agent thread. */
export interface ConversationMessage {
  id: string;
  taskId: string;
  conversationId: string;
  authorId: string;
  authorKind: ConversationAuthorKind;
  content: string;
  mentions: Mention[];
  createdAt: string;
}

/** The routing result produced when a message contains one or more @mentions. */
export interface MentionRoute {
  conversationId: string;
  messageId: string;
  recipientId: string;
  recipientKind: "orchestrator" | "agent";
  handle: string;
}

export interface TaskPlan {
  goal: string;
  subtasks: Subtask[];
}

export interface Subtask {
  id: string;
  title: string;
  capability: "docs" | "browser" | "shell" | "files" | "integration" | "verify";
  dependsOn: string[];
  riskLevel: "low" | "medium" | "high";
  successCriteria: string;
  /** Planner-selected roster key. New plans must provide this explicitly. */
  agentTemplate?: string;
  /** Short model-generated explanation for the assignment. */
  routingReason?: string;
  /** Model dynamically assigned by the planner. */
  model?: string;
  /** Short explanation of why this model fits the subtask. */
  modelReason?: string;
  /** Artifacts generated by the subtask execution. */
  artifacts?: ArtifactRef[];
  state: "pending" | "running" | "completed" | "failed";
  assignedTo?: string;
  result?: string;
}

export interface ToolCall {
  id: string;
  capability: string;
  method: string;
  args: Record<string, any>;
}

export type AgentMessage =
  | { kind: "status"; from: string; taskId: string; state: "working" | "blocked" | "done"; note?: string }
  | { kind: "result"; from: string; taskId: string; artifacts: ArtifactRef[]; summary: string; incomplete?: boolean }
  | { kind: "info_request"; from: string; to: string; question: string }
  | { kind: "info_reply"; from: string; to: string; answer: string }
  | { kind: "help_request"; from: string; to: "orchestrator"; problem: string }
  | { kind: "approval_request"; from: string; to: "orchestrator"; action: ToolCall }
  | { kind: "thought"; from: string; content: string };

export interface LedgerEntry {
  timestamp: string;
  step: number;
  facts: string[];
  assumptions: string[];
  subtaskStates: Record<string, "pending" | "running" | "completed" | "failed">;
  nextStepStrategy: string;
}
