import React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { MessageType } from "../chat-content/enums/message.enums";
import { WorkspaceShell } from "./WorkspaceShell";

const meta = { title: "v2/Workspace/Chat Workspace", component: WorkspaceShell, parameters: { layout: "fullscreen" }, args: { title: "Implement the workspace shell", homeTitle: "New chat", homePlaceholder: "What would you like YAAA to work on?", responseText: "The workspace shell is ready. This is a dummy YAAA response.", initialProjects: [{ id: "yaaa", name: "YAAA", temporary: false }, { id: "scratch", name: "Temporary chats", temporary: true }], initialChats: [{ id: "shell-chat", title: "Implement the workspace shell", projectId: "yaaa" }, { id: "review-chat", title: "Review runtime changes", projectId: "yaaa" }, { id: "quick-chat", title: "Quick question" }], activeChatId: "shell-chat", initialMessages: [{ type: MessageType.ResponseMessage, userName: "YAAA", messageBody: { kind: "text", content: "Welcome to the workspace." } }], initialBots: [{ id: "researcher", name: "Researcher", status: "online" as const, contextWindow: { used: 420, limit: 1000 }, role: "Worker", model: "gpt-5" }], initialFolders: [{ id: "project", name: "Project folder", path: "/project", kind: "agent-space" as const, children: [{ id: "src", name: "src", path: "/project/src", type: "folder" as const, children: [{ id: "runtime", name: "runtime.ts", path: "/project/src/runtime.ts", type: "file" as const, change: "modified" as const }] }] }], initialSideTabs: [{ id: "logs", title: "Researcher logs", content: [{ id: "one", title: "Latest event", content: "Scanning project files…" }] }, { id: "files", title: "Affected files", content: [{ id: "two", content: "src/runtime.ts" }] }] } } satisfies Meta<typeof WorkspaceShell>;
export default meta;
type Story = StoryObj<typeof meta>;
export const ThreeColumnWorkspace: Story = { render: (args) => <div style={{ height: "100dvh", minHeight: 0 }}><WorkspaceShell {...args} /></div> };
